----  CREAZIONE TABELLA

DROP TABLE IF EXISTS CONTO_CONFIGURATION;
 
CREATE TABLE CONTO_CONFIGURATION (
  OPERATION VARCHAR(3) NOT NULL,
  MESSAGE_IN VARCHAR(2000) NOT NULL,
  MESSAGE_OUT_FROM_BUS VARCHAR(2000) NOT NULL
);

DROP TABLE IF EXISTS CONTO_INDIRIZZI;

CREATE TABLE CONTO_INDIRIZZI (
  OPERATION VARCHAR(3) NOT NULL,
  AMBIENTE VARCHAR(10) NOT NULL,
  INDIRIZZO VARCHAR(1000) NOT NULL,
  HTTP_METHOD  VARCHAR(10) NOT NULL DEFAULT 'POST'
);

DROP TABLE IF EXISTS CONTO_TRANSACTION;

CREATE TABLE CONTO_TRANSACTION (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  transactionId VARCHAR(20) NOT NULL,
  operationId VARCHAR(20) NOT NULL,
  accountingDate DATE NOT NULL,
  valueDate DATE NOT NULL,
  amount NUMERIC NOT NULL,
  currency VARCHAR(3) NOT NULL,
  description VARCHAR(3000) DEFAULT NULL
);